require('../src/app')
require('./auth/auth_test')
require('./profile/profile_test')
require('./calendar/calendar_test')
require('./timetable/timetable_test')
require('./analytics/analytics_test')
require('./student/student_test')
require('./odandleave/odandleave_test')
